#include <core/QEI_driver/QEI_AngularSpeed.hpp>

namespace core {
namespace QEI_driver {
CORE_CONFIGURATION_DEFAULT_BEGIN()
CORE_CONFIGURATION_DEFAULT_FIELD(ticks, FLOAT32, 1, 1.0f)
CORE_CONFIGURATION_DEFAULT_FIELD(period, UINT16, 1, 50)
CORE_CONFIGURATION_DEFAULT_FIELD(invert, UINT8, 1, 0)
CORE_CONFIGURATION_DEFAULT_END()

CORE_CONFIGURATION_CONSTRUCTOR_BEGIN(QEI_AngularSpeed)
CORE_CONFIGURATION_CONSTRUCTOR_FIELD(ticks),
CORE_CONFIGURATION_CONSTRUCTOR_FIELD(period),
CORE_CONFIGURATION_CONSTRUCTOR_FIELD(invert)
CORE_CONFIGURATION_CONSTRUCTOR_END()

CORE_CONFIGURATION_MAP_BEGIN(QEI_AngularSpeed)
CORE_CONFIGURATION_MAP_ENTRY(QEI_AngularSpeed, period, UINT16, 1)
CORE_CONFIGURATION_MAP_ENTRY(QEI_AngularSpeed, ticks, FLOAT32, 1)
CORE_CONFIGURATION_MAP_ENTRY(QEI_AngularSpeed, invert, UINT8, 1)
CORE_CONFIGURATION_MAP_END()
}
}
